package com.lj.ibe.util;

import java.util.Arrays;
import java.util.List;

public class constant {
    public static List<String> SPECAILFAREGRP = Arrays.asList(
            "JINMARKET", "JINMARKETK1", "JINMARKETK2", "JINMARKETK3", "JINMARKETW1", "JINMARKETW2", "JINMARKETW3"
            , "SLIMJEANS", "SLIMJEANSK1", "SLIMJEANSK2", "SLIMJEANSK3", "SLIMJEANSW1", "SLIMJEANSW2", "SLIMJEANSW3"
            , "THISISIT", "THISISITK1", "THISISITK2", "THISISITK3"
            , "ONPROMO", "ONPROMOK1", "ONPROMOK2", "ONPROMOK3", "ONPROMOW1", "ONPROMOW2", "ONPROMOW3"
            , "SPDISC", "SPDISCK1", "SPDISCK2", "SPDISCK3", "SPDISCW1", "SPDISCW2", "SPDISCW3"
            , "SUPERLOWK1", "SUPERLOWK2", "SUPERLOWK3", "SUPERLOWW1", "SUPERLOWW2", "SUPERLOWW3"
            , "IJINMKT", "IJINMKTK1", "IJINMKTK2", "IJINMKTK3", "IJINMKTW1", "IJINMKTW2", "IJINMKTW3"
            , "ISLIMJ", "ISLIMJK1", "ISLIMJK2", "ISLIMJK3", "ISLIMJW1", "ISLIMJW2", "ISLIMJW3"
            , "IPROMO", "IPROMOK1", "IPROMOK2", "IPROMOK3", "IPROMOW1", "IPROMOW2", "IPROMO3"
            , "ITHIS", "ITHISK1", "ITHISK2", "ITHISK3", "ITHISW1", "ITHISW2", "ITHISW3"
    );
}
